all:
	g++ -g -o ./test -I /usr/pgsql-9.3/include/ main.c CNConfig.cpp cJSON.c PGDatabase.cpp PGRecordset.cpp protocolresolve.c dataprocess.c udpreceiver.c toolkit.c -L /usr/pgsql-9.3/lib/ -lpq -lm -pthread

